# 这里是完整的配置项，除了标注为 `必填` 的选项外，都可以修改或删除。
# 缺少的选项会使用内部的配置（见 `application.yml`）。
#
# 若 jar 包同级目录下没有此文件，会自动生成。
#
# 可以在运行 jar 包时传入参数来指定配置文件：
# `java -jar entangle.jar --entangle.configure.path=C:/example/my-configuration.yml`


# 日志
logging:
  level:
    root: warn
    me.zephyr: info

entangle:
  # 必填
  targetHost:
  # 连接超时
  connectTimeOut: 5000

clipboard:
  # 剪贴板内容发送开关（对方端点要打开接收开关才能真正发送出去）
  sendSwitch: true
  # 剪贴板内容接受开关（对方端点要打开发送开关才能真正接收到）
  receiveSwitch: true
  # 操作剪贴板时，偶尔会因为剪贴板被占用而操作失败，程序会自动重试
  retry:
    # 重试次数
    times: 10
    # 重试间隔，单位毫秒（1 秒 = 1000 毫秒）
    interval: 50